plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = "${project.mod_version}+fabric26.1"
group = project.mod_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
    maven { url = 'https://api.modrinth.com/maven' }
    maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    implementation "maven.modrinth:geckolib:yUpAp23B"
    implementation "com.electronwill.night-config:toml:3.8.1"
    implementation "com.electronwill.night-config:core:3.8.1"
    include "com.electronwill.night-config:toml:3.8.1"
    include "com.electronwill.night-config:core:3.8.1"
    compileOnly files("C:/Users/user/.gradle/caches/fabric-loom/minecraftMaven/net/minecraft/minecraft-clientonly-deobf/${project.minecraft_version}/minecraft-clientonly-deobf-${project.minecraft_version}.jar")
    compileOnly "com.google.code.findbugs:jsr305:3.0.2"
}

loom {
    splitEnvironmentSourceSets()
    mods {
        jeg {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

processResources {
    inputs.property "version", project.mod_version
    inputs.property "minecraft_version_range", project.minecraft_version_range
    filesMatching("fabric.mod.json") {
        expand(
                "version": project.mod_version,
                "minecraft_version_range": project.minecraft_version_range
        )
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }
}
